typography_spectrum: 0.5983059501741081
color:
  saturation: 0.20893412921577692
  brandStrength: 0.3910353390965611
  rhythmicContrast: 0.9666064651682973
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  lightness: 0.2863624142482877
layout_spectrum: 0.3415696343872696
name: Rossoow
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Jake Xon
description: Grrrrrr
