title: Jake Xon
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8386194
  brandStrength: 0.5699627
  lightness: 1
  brandColors:
    - '#5E6472'
    - '#8F94A7'
    - '#6E854F'
    - '#41342C'
    - '#9FC28C'
  rhythmicContrast: 1
typography_spectrum: 0.375
description: Grrrrrr
layout_spectrum: 0.1218638
name: Rossoow
