collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1632463
  brandStrength: 0.6543843
  lightness: 0.7266791
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  rhythmicContrast: 0.2798508
typography_spectrum: 0.1203358
layout_spectrum: 0.1431903
name: Rossoo
